---
channel: edge
addons:
  paperless-ngx:
    repository: BenoitAnastay/paperless-home-assistant-addon
    target: paperless_ngx
    image: ghcr.io/benoitanastay/paperless_ngx/{arch}
  dashy:
    repository: BenoitAnastay/dashy-home-assistant-addon
    target: dashy
    image: ghcr.io/benoitanastay/dashy/{arch}
  authelia:
    repository: BenoitAnastay/authelia-home-assistant-addon
    target: authelia
    image: ghcr.io/benoitanastay/authelia/{arch}
